server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    root /var/www/mbclaw;
    autoindex on;
    client_max_body_size 200M;

    location = /mbclaw-root-latest.apk {
    }
    location = /mbclaw-linux-full-arm64.tar.gz {
        return 301 http://8.130.42.188/mbclaw-linux-full-arm64.tar.gz;
    }
    location = /mbclaw-lite-latest.apk {
        return 301 http://8.130.42.188/mbclaw-lite-latest.apk;
    }

    location /status {
        default_type application/json;
        return 200 '{"status":"ok"}';
    }

    location /miclaw/ {
        proxy_pass http://127.0.0.1:8765/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8765/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
    }

    location /v1/ {
        proxy_pass http://127.0.0.1:8765/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_buffering off;
    }

    location / {
        add_header Cache-Control "no-store";
        try_files $uri $uri/ =404;
    }
}
